Go Modules support
plutov/paypal pull request #110
Opened 2019-08-24 17:02 UTC by roopakv

We have already released v2, which means things are slightly different for us.

Based on the suggestions here: https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher

We will go with the branch strategy.

We will not create a new branch since we dont have CLI this should not break anyone since there is no reason to go get -u this package.

Once we have this in place we can start a bit of refactoring :)

2019-08-24 18:51 UTC, plutov commented
Hi @roopakv, since you're a contributor you can just create a branch directly in this repo, not in a fork, that will be easier for me to checkout it and test.

Also, why did you remove `paypal` from `billing_test.go`. It's a file for godoc example, IMO it should have `paypal.` because that's what users will use.

The module file looks good. Will I need to push a v3.0.0 tag after merge?

2019-08-24 21:04 UTC, roopakv commented
@plutov it is a branch in this repo :) i just namespace my branches with `roopakv/`. [Link](https://github.com/plutov/paypal/tree/roopakv/go_mod) to branch in this repo

i moved billing_test to paypal package. Since we need to support tests in different go versions, the import for the test doesnt work.

I'm open to other suggestions as well

2019-08-25 20:13 UTC, plutov commented
But now `BillingExample` function is available for the clients, which is not needed. I guess we can just remove this file :)

2019-08-26 07:26 UTC, plutov requested changes

2019-08-26 07:26 UTC, plutov commented on example_test.go
> +	c, err := NewClient("clientID", "secretID", APIBaseSandBox)
Since it's an example, this function shouldn't be exposed in the `paypal` package, but should be visible only in godoc.

2019-08-26 07:26 UTC, plutov commented on billing_test.go
> +func billingExample() {
Since it's an example, this function shouldn't be exposed in the `paypal` package, but should be visible only in godoc.

2019-08-26 16:34 UTC, roopakv commented
@plutov I was looking for what other packages do. I sort of feel like testing go, 1.10+ will actually make our package neater, rather than testing 1.5 which is why we have to move packages for the tests.

thoughts

example of a package that moved to go modules: https://github.com/olivere/elastic

2019-08-26 17:47 UTC, plutov commented
Yes, we basically need to put all examples into example_test.go file - like it's done here - https://github.com/olivere/elastic/blob/release-branch.v7/example_test.go

2019-08-27 10:38 UTC, merged