Potential fix for Issue 230
plutov/paypal pull request #231
Opened 2021-11-07 19:41 UTC by madprogramer

#### What does this PR do?
`VerifyWebhookSignature` now returns an error if an *http.Request with an empty body is passed.

#### Where should the reviewer start?
Only a few lines were added to `webhooks.go`. Feel free to write new unit tests for `VerifyWebhookSignature`.

#### How should this be manually tested?
`c.VerifyWebhookSignature` should be passed an *http.Request  with an empty body.

#### Any background context you want to provide?
Issue #230

2021-11-08 08:24 UTC, plutov requested changes

2021-11-08 08:24 UTC, plutov commented on webhooks.go
> +	else{
Please keep else on the same line with closing bracket and add a space before opening bracket.

2021-11-08 09:21 UTC, madprogramer reviewed
Fixed else syntax on line 100/101

2021-11-08 11:36 UTC, plutov reviewed
Please also add spaces: `} else {`

2021-11-10 22:34 UTC, madprogramer reviewed
Added spaces

2021-11-10 22:36 UTC, madprogramer commented
Added spaces :)

2021-11-11 11:48 UTC, plutov approved these changes

2021-11-11 11:48 UTC, merged